export const REGISTERATION_QUESTIONS = [
    {
        answer_choice_1: "< 3",
        answer_choice_2: "3-5",
        answer_choice_3: "5-10",
        answer_choice_4: "10+",
        answer_choice_5: "",
        answer_choice_6: "",
        answer_choice_7: "",
        answer_choice_8: "",
        answer_choice_9: "",
        answer_choice_10: "",
        answer_type: 1,
        category: 2,
        content: "What are the number of investments you have made in the last 365 days?",
        id: 4,
        is_deleted: false,
        last_changed_by_id: 842,
        question: "How many investments have you made in the past year?",
        question_set: 0,
        slider_display: false,
        sort_order: 2,
        visible: true,
    },
    {
        answer_choice_1: "< $5,000",
        answer_choice_2: "$5,000-$15,000",
        answer_choice_3: "$15,000-$30,000",
        answer_choice_4: "$30,000-$50,000",
        answer_choice_5: "$50,000+",
        answer_choice_6: "",
        answer_choice_7: null,
        answer_choice_8: null,
        answer_choice_9: null,
        answer_choice_10: null,
        answer_type: 1,
        category: 2,
        content: "What amount do you typically invest (on average) in each investment opportunity you undertake?",
        id: 5,
        is_deleted: false,
        last_changed_by_id: 842,
        question: "What is your average investment amount per investment?",
        question_set: 0,
        representative_image: null,
        slider_display: false,
        sort_order: 5,
        type_3_range: null,
        type_3_total: null,
        visible: true,
    },
    {
        answer_choice_1: "< 10%",
        answer_choice_2: "10-20%",
        answer_choice_3: "20-30%",
        answer_choice_4: "30-40%",
        answer_choice_5: "40-50%",
        answer_choice_6: "50+ %",
        answer_choice_7: null,
        answer_choice_8: null,
        answer_choice_9: null,
        answer_choice_10: null,
        answer_type: 1,
        category: 3,
        content: "How much do you set aside for investments on an annual basis?",
        id: 16,
        is_deleted: false,
        last_changed_by_id: 842,
        question: "What percentage of your annual income is saved for investing?",
        question_set: 0,
        representative_image: null,
        slider_display: false,
        sort_order: 5,
        type_3_range: null,
        type_3_total: null,
        visible: true,
    },
    {
        answer_choice_1: "Cash Savings or Fixed Deposits",
        answer_choice_2: "Bonds",
        answer_choice_3: "Unit Trusts",
        answer_choice_4: "Equities",
        answer_choice_5: "Other",
        answer_choice_6: "",
        answer_choice_7: "",
        answer_choice_8: "",
        answer_choice_9: "",
        answer_choice_10: "",
        answer_type: 2,
        category: 2,
        content: "Which investment vehicle(s) have you had previous experience in?",
        id: 2,
        is_deleted: false,
        last_changed_by_id: 2,
        question: "I have experience in the following investment(s):",
        question_set: 0,
        representative_image: null,
        slider_display: false,
        sort_order: 1,
        total_result_set_rows: 47,
        type_3_range: null,
        type_3_total: null,
        visible: false,
    },
    {
        answer_choice_1: "Cash",
        answer_choice_2: "Bonds",
        answer_choice_3: "Equities",
        answer_choice_4: "Real Estate",
        answer_choice_5: "ETFs",
        answer_choice_6: "Private Equity",
        answer_choice_7: null,
        answer_choice_8: null,
        answer_choice_9: null,
        answer_choice_10: null,
        answer_type: 3,
        category: 5,
        content: "",
        id: 31,
        is_deleted: false,
        last_changed_by_id: 1,
        question: "The trust entityâ€™s current investment portfolio is made up of:",
        question_set: 0,
        representative_image: null,
        slider_display: false,
        sort_order: 11,
        type_3_range: null,
        type_3_total: null,
        visible: true,
    }
]

export const QUESTION_ANSWERS = [
    {
        answer_text: null,
        answer_type: 1,
        category: 2,
        id: 4,
        question: "How many investments have you made in the past year?",
        selectedOption: null,
        selected_value1: null,
        selected_value2: null,
        selected_value3: null,
        selected_value4: null,
        selected_value5: null,
        selected_value6: null,
        selected_value7: null,
        selected_value8: null,
        selected_value9: null,
        selected_value10: null,
    },
    {
        answer_text: null,
        answer_type: 1,
        category: 2,
        id: 5,
        question: "What is your average investment amount per investment?",
        selectedOption: null,
        selected_value1: null,
        selected_value2: null,
        selected_value3: null,
        selected_value4: null,
        selected_value5: null,
        selected_value6: null,
        selected_value7: null,
        selected_value8: null,
        selected_value9: null,
        selected_value10: null,
    },
    {
        answer_text: null,
        answer_type: 1,
        category: 3,
        id: 16,
        question: "What percentage of your annual income is saved for investing?",
        selectedOption: null,
        selected_value1: null,
        selected_value2: null,
        selected_value3: null,
        selected_value4: null,
        selected_value5: null,
        selected_value6: null,
        selected_value7: null,
        selected_value8: null,
        selected_value9: null,
        selected_value10: null,
    },
    {
        answer_text: null,
        answer_type: 2,
        category: 2,
        id: 2,
        question: "Which investment vehicle(s) have you had previous experience in?",
        selectedOption: null,
        selected_value1: true,
        selected_value2: false,
        selected_value3: false,
        selected_value4: false,
        selected_value5: false,
        selected_value6: false,
        selected_value7: false,
        selected_value8: false,
        selected_value9: false,
        selected_value10: false,
    },
    {
        answer_text: null,
        answer_type: 3,
        category: 5,
        id: 31,
        question: "The trust entityâ€™s current investment portfolio is made up of:",
        selectedOption: null,
        selected_value1: null,
        selected_value2: null,
        selected_value3: null,
        selected_value4: null,
        selected_value5: null,
        selected_value6: null,
        selected_value7: null,
        selected_value8: null,
        selected_value9: null,
        selected_value10: null
    },
]

export const USER_ANSWERS = [
    {
        answer_text: "3-5",
        answer_type: 1,
        category: 2,
        entity_id: null,
        id: 4078,
        is_confirmed: false,
        is_deleted: false,
        last_changed_by_id: 936,
        notes: null,
        question_id: 4,
        question_text: "How many investments have you made in the past year?",
        status: 0,
        user_id: 936,
    }
]

export const CURRENT_ANSWERS = [
    "< 3",
    "3-5",
    "5-10",
    "10+" 
]